services:
  # napcat:
  #   image: mlikiowa/napcat-docker:v4.17.55
  #   container_name: napcat
  #   restart: always
  #   mac_address: 02:42:ac:11:00:02
  #   environment:
  #     - ACCOUNT=${QQBOT_ACCOUNT}
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #     - 6099:6099
  #   volumes:
  #     - ./napcat/config:/app/napcat/config
  #     - ./ntqq:/app/.config/QQ

  bot:
    build: .
    container_name: bilibili-gachi-bot
    restart: always
    env_file:
      - .env
    environment:
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
