name: Sync to HF

on:
  push:
    branches:
      - hf

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Push to Hg
        env:
          HG_URL: ${{ secrets.HF_URL }}
        run: |
          git remote set-url origin ${HF_URL} 
          git push --force origin HEAD:main